Plugin/mlflow custom flavor - fixed small bug
DAGWorks-Inc/hamilton pull request #1068
Opened 2024-07-26 20:53 UTC by jernejfrank

Thanks for adding the custom flavor option to mlflow. I tested it and only the flavor specific kwargs somehow got mixed up and tried to be called somewhere else which lead to a fatal error.

## Changes
- renamed class attribute to avoid conflicting calls

## How I tested this
- added unit test that doubles as minimal example for reproducing the error

## Notes
- only tested the DataSaver (due to internal legacy structure, DataLoader is not utilised/hard to implement)

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

2024-07-26 21:02 UTC, skrawcz commented
Thanks @jernejfrank ! For the pre-commit failure you just need to do something like:

`pip install pre-commit`
`pre-commit install`
`pre-commit run --all-files`
And then check that change in  and you should be good to go. Thanks for the fix!

2024-07-26 21:32 UTC, skrawcz commented
I'll plan to push this in the release on Monday. If you don't get to the `pre-commit` before I'll do it. Thanks!

2024-07-26 21:35 UTC, skrawcz requested changes
looks good. just a few things:

1. pre-commit.
2. you added some files in by accident I assume from the hamilton_ui example.

2024-07-26 21:35 UTC, skrawcz commented on examples/hamilton_ui/data_set_v1.parquet
delete this please

2024-07-26 21:35 UTC, skrawcz commented on examples/hamilton_ui/lr_model.pkl
delete this change please

2024-07-26 21:35 UTC, skrawcz commented on examples/hamilton_ui/svm_model.pkl
delete this change please

2024-07-26 21:50 UTC, jernejfrank commented on examples/hamilton_ui/data_set_v1.parquet
missed this got generated, sorry.

2024-07-26 21:50 UTC, jernejfrank commented on examples/hamilton_ui/lr_model.pkl
same here.

2024-07-26 21:50 UTC, jernejfrank commented on examples/hamilton_ui/svm_model.pkl
and here.

2024-07-27 03:36 UTC, skrawcz approved these changes

2024-07-27 03:37 UTC, skrawcz commented
Thanks @jernejfrank !

2024-07-27 03:37 UTC, merged