Created Docs-node-reuse.md as the guide for node reuse in hamilton library
DAGWorks-Inc/hamilton pull request #1192
Opened 2024-10-17 12:23 UTC by danieltayal07

Documentation for guide of node reuse in hamilton library

--- PR TEMPLATE INSTRUCTIONS (1) ---

Looking to submit a Hamilton Dataflow to the sf-hamilton-contrib module? If so go the the `Preview` tab and select the appropriate sub-template:
* [sf-hamilton-contrib template](?expand=1&template=HAMILTON_CONTRIB_PR_TEMPLATE.md)

Else, if not, please remove this block of text.

--- PR TEMPLATE INSTRUCTIONS (2) ---

[Short description explaining the high-level reason for the pull request]

## Changes

made a md file for the guide of node reuse

## How I tested this

i tested it by asking chat gpt to help me test it in my computer and then tested it in my computer

## Notes

tried my best to make the shortest and the most concise to the point guide for node reuse. 
Personally i never used hamilton library but now after seeing all the md's and the codes and how it makes out lives easier.
I am a proud user.

## Checklist

- [✅ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [✅ ] Changes are limited to a single goal (no scope creep)
- [ ✅] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ✅] Any _change_ in functionality is tested
- [ ✅] New functions are documented (with a description, list of inputs, and expected output)
- [✅ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ✅] Project documentation has been updated if adding/changing functionality.

2024-10-17 12:26 UTC, danieltayal07 commented
please add 
hacktoberfest2024
and hacktoberfest tag in this so it is counted in hacktoberfest2024

thank you!

2024-10-17 23:53 UTC, skrawcz requested changes
@danieltayal07 please see the #1045 issue. This doesn't fulfill those requirements and is not even correct hamilton code.

2024-10-18 03:41 UTC, danieltayal07 commented
Sorry for the mistake

I'll fix them and follow your requirements by the end of the day

2024-10-18 08:47 UTC, danieltayal07 commented
Hi @skrawcz I have tried to make better changes now, please check 

if not helpful please give feedback i'll try my best to mould it!

Thanks!

2024-10-18 18:38 UTC, elijahbenizzy commented on docs/how-tos/guide-reuse-nodes
> +    graph = Graph()
What framework is this using? Very curious, I'm not familiar with this API.

2024-10-18 19:19 UTC, skrawcz requested changes
@danieltayal07 sorry but you're actually going to have to understand how Hamilton works to know whether the documentation is valid. Only using an LLM to generate this documentation isn't sufficient for this task.

2024-10-18 20:39 UTC, danieltayal07 commented
Yes i will try to find something easier than this to contribute to in Hamilton if possible, i apologise.

2024-10-19 00:29 UTC, skrawcz commented
@danieltayal07 I have this issue which I think is perfect for you - https://github.com/DAGWorks-Inc/burr/issues/404 (it's in Hamilton's sister repo). Please comment if you'd like it.

2024-10-19 05:23 UTC, danieltayal07 commented
yes yes i would love to!!

2024-10-21 16:47 UTC, closed without merging