Update pandas_extensions.py
DAGWorks-Inc/hamilton pull request #412
Opened 2023-10-01 16:49 UTC by 149189

--- PR TEMPLATE INSTRUCTIONS (1) ---

Looking to submit a Hamilton Dataflow to the sf-hamilton-contrib module? If so go the the `Preview` tab and select the appropriate sub-template:
* [sf-hamilton-contrib template](?expand=1&template=HAMILTON_CONTRIB_PR_TEMPLATE.md)

Else, if not, please remove this block of text.

--- PR TEMPLATE INSTRUCTIONS (2) ---

[Short description explaining the high-level reason for the pull request]

## Changes

1. Added `PandasTableReader` class in `pandas_extensions.py` for reading tabular data using `pandas.read_table`.
2. Implemented necessary methods to facilitate the loading of data.
3. Registered the `PandasTableReader` class in the data loader registry.

**Functionality:**

The `PandasTableReader` class allows reading tabular data with flexible loading options using `pandas.read_table`. It inherits from the `DataLoader` class and provides an easy way to load data into a DataFrame.

**Documentation:**

Updated the `data_loader` module documentation to include information about the new `PandasTableReader` class and its usage for loading tabular data.

**Reviewer Note:**

Please review the changes made in `pandas_extensions.py` and the associated tests in `test_pandas_extensions.py`. Feedback and suggestions are welcome.

## How I tested this

Added a unit test (`test_read_table`) in `test_pandas_extensions.py` to validate the functionality of the `PandasTableReader` class. The test covers loading tabular data and comparing the expected DataFrame with the loaded DataFrame.

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

2023-10-03 09:48 UTC, 149189 commented
@skrawcz Hey! I have made some Changes can you review my code please i am not understanding why the isort failed

2023-10-03 17:06 UTC, skrawcz requested changes
Thanks for putting this up. To merge this, we need a few changes. See comments.

2023-10-03 17:06 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +from io import BytesIO, BufferedReader
this is a redefinition of the above. remove

2023-10-03 17:06 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +import pandas as pd
this is already done below. remove.

2023-10-03 17:06 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +from pathlib import Path
these all look like redefinitions and not required.

2023-10-03 17:06 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +class PandasTableReader(DataLoader):
This should be decorated with a dataclass, and look like the other classes.

2023-10-03 17:06 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +        data = read_table(filepath_or_buffer, **kwargs)
this should be pd.read_table, not importing it directly.

2023-10-03 17:06 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +        return data, {}
this should use the metadata utility like the others are using to provide metadata on the file being loaded.

2023-10-03 18:30 UTC, 149189 commented
@skrawcz Bro I made all the changes you told and the branch has been merged. Thanks for this experience this was my first contribution!!

2023-10-18 20:40 UTC, skrawcz commented
@149189 are you still working on this?

2023-11-02 20:26 UTC, skrawcz commented
closing because I haven't heard back.

2023-11-02 20:26 UTC, closed without merging