Update pandas_extensions.py
DAGWorks-Inc/hamilton pull request #428
Opened 2023-10-03 18:40 UTC by 149189

--- PR TEMPLATE INSTRUCTIONS (1) ---

Looking to submit a Hamilton Dataflow to the sf-hamilton-contrib module? If so go the the `Preview` tab and select the appropriate sub-template:
* [sf-hamilton-contrib template](?expand=1&template=HAMILTON_CONTRIB_PR_TEMPLATE.md)

Else, if not, please remove this block of text.

--- PR TEMPLATE INSTRUCTIONS (2) ---

[Short description explaining the high-level reason for the pull request]

## Changes
Removed the extra import pandas as pd.
Removed the redefined code.
The class PandasTableReader(DataLoader) is now decorated with dataclass.
pd.read_table is added.
Large Dict are made small.
Used the metadata utility like the others are using to provide metadata on the file being loaded.

## How I tested this

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

2023-10-03 18:42 UTC, 149189 commented
@skrawcz Hey! Can you review my code I made all the changes that you told bro.

2023-10-03 19:05 UTC, skrawcz requested changes
there is no unit test here. please also investigate and correct the test failures.

2023-10-03 19:05 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +    print("Metadata:", metadata)
why is this code here? please remove it.

2023-10-03 19:05 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +        kwargs = {
this does not look like the other classes. It should look something [like this](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py#L265-L301).

2023-10-03 19:05 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +        return cls.reader_name
This should just be:

```python
    @classmethod
    def name(cls) -> str:
        return "feather"
```

2023-10-03 19:05 UTC, skrawcz commented on hamilton/plugins/pandas_extensions.py
> +        return data, metadata
this code does not work. Please correct.

2023-10-25 03:37 UTC, skrawcz commented
Let me know if you're still working on this else I will close this PR and reassign the issue. Thanks.

2023-11-02 20:26 UTC, skrawcz commented
closing because I haven't heard back.

2023-11-02 20:26 UTC, closed without merging